version: '3.8'
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tempPassword
      - POSTGRES_DB=lift_tracker
    healthcheck:
      test: 'pg_isready -U postgres -d lift_tracker'
      interval: 10s
      timeout: 3s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_SOURCE=postgresql://postgres:tempPassword@postgres:5432/lift_tracker?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ['/app/wait-for.sh', 'postgres:5432', '--', '/app/start.sh']
    command: ['/app/main']
