// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: account.sql

package db

import (
	"context"
	"time"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
  lifter,
  age,
  weight,
  start_date
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, lifter, age, weight, start_date
`

type CreateAccountParams struct {
	Lifter    string    `json:"lifter"`
	Age       int32     `json:"age"`
	Weight    int32     `json:"weight"`
	StartDate time.Time `json:"start_date"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.Lifter,
		arg.Age,
		arg.Weight,
		arg.StartDate,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Lifter,
		&i.Age,
		&i.Weight,
		&i.StartDate,
	)
	return i, err
}
