// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	Email             string    `json:"email"`
	Password          string    `json:"password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	Weight            float32   `json:"weight"`
	BodyFat           float32   `json:"body_fat"`
	StartDate         time.Time `json:"start_date"`
}

type Category struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

type Exercise struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	MuscleGroup string `json:"muscle_group"`
	Category    string `json:"category"`
}

type Lift struct {
	ID           uuid.UUID `json:"id"`
	ExerciseName string    `json:"exercise_name"`
	WeightLifted float32   `json:"weight_lifted"`
	Reps         int16     `json:"reps"`
	UserID       uuid.UUID `json:"user_id"`
	WorkoutID    uuid.UUID `json:"workout_id"`
}

type MuscleGroup struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

type Workout struct {
	ID         uuid.UUID `json:"id"`
	StartTime  time.Time `json:"start_time"`
	FinishTime time.Time `json:"finish_time"`
	UserID     uuid.UUID `json:"user_id"`
}
