// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID `json:"id"`
	Lifter    string    `json:"lifter"`
	BirthDate time.Time `json:"birth_date"`
	Weight    int32     `json:"weight"`
	StartDate time.Time `json:"start_date"`
}

type Exercise struct {
	ID           int64  `json:"id"`
	ExerciseName string `json:"exercise_name"`
	MuscleGroup  string `json:"muscle_group"`
}

type Lift struct {
	ID           int64     `json:"id"`
	ExerciseName string    `json:"exercise_name"`
	Weight       float32   `json:"weight"`
	Reps         int32     `json:"reps"`
	DateLifted   time.Time `json:"date_lifted"`
	UserID       uuid.UUID `json:"user_id"`
	SetID        uuid.UUID `json:"set_id"`
}

type MuscleGroup struct {
	ID        int64  `json:"id"`
	GroupName string `json:"group_name"`
}

type Set struct {
	ID uuid.UUID `json:"id"`
}
