// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateLift(ctx context.Context, arg CreateLiftParams) (Lift, error)
	CreateLifts(ctx context.Context, arg CreateLiftsParams) ([]Lift, error)
	CreateMuscleGroup(ctx context.Context, name string) (MuscleGroup, error)
	CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) (Account, error)
	DeleteCategory(ctx context.Context, id int16) error
	DeleteExercise(ctx context.Context, name string) error
	DeleteGroup(ctx context.Context, name string) (MuscleGroup, error)
	DeleteLift(ctx context.Context, id uuid.UUID) error
	DeleteWorkout(ctx context.Context, id uuid.UUID) error
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	GetCategory(ctx context.Context, id int16) (Category, error)
	GetExercise(ctx context.Context, name string) (Exercise, error)
	GetLift(ctx context.Context, arg GetLiftParams) (Lift, error)
	GetMuscleGroup(ctx context.Context, name string) (MuscleGroup, error)
	GetMuscleGroups(ctx context.Context) ([]MuscleGroup, error)
	GetWorkout(ctx context.Context, id uuid.UUID) ([]GetWorkoutRow, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListByMuscleGroup(ctx context.Context, arg ListByMuscleGroupParams) ([]Exercise, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListExercises(ctx context.Context, arg ListExercisesParams) ([]Exercise, error)
	ListLifts(ctx context.Context, arg ListLiftsParams) ([]Lift, error)
	ListPRs(ctx context.Context, arg ListPRsParams) ([]Lift, error)
	ListPRsByExercise(ctx context.Context, arg ListPRsByExerciseParams) ([]Lift, error)
	ListPRsByMuscleGroup(ctx context.Context, arg ListPRsByMuscleGroupParams) ([]ListPRsByMuscleGroupRow, error)
	ListWorkouts(ctx context.Context, arg ListWorkoutsParams) ([]Workout, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error)
	UpdateFinishTime(ctx context.Context, arg UpdateFinishTimeParams) (Workout, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (MuscleGroup, error)
	UpdateLift(ctx context.Context, arg UpdateLiftParams) (Lift, error)
	UpdateWeight(ctx context.Context, arg UpdateWeightParams) error
}

var _ Querier = (*Queries)(nil)
