// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: set.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSet = `-- name: CreateSet :one
INSERT INTO set (user_id) 
VALUES ($1)
RETURNING id, user_id
`

func (q *Queries) CreateSet(ctx context.Context, userID uuid.UUID) (Set, error) {
	row := q.db.QueryRowContext(ctx, createSet, userID)
	var i Set
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const deleteSet = `-- name: DeleteSet :exec
DELETE FROM set WHERE id = $1
`

func (q *Queries) DeleteSet(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSet, id)
	return err
}

const getLiftSets = `-- name: GetLiftSets :many
SELECT exercise_name, weight, reps, date_lifted, set_id
FROM set JOIN lift ON set.id = lift.set_id WHERE set.id = $1
`

type GetLiftSetsRow struct {
	ExerciseName string    `json:"exercise_name"`
	Weight       float32   `json:"weight"`
	Reps         int32     `json:"reps"`
	DateLifted   time.Time `json:"date_lifted"`
	SetID        uuid.UUID `json:"set_id"`
}

func (q *Queries) GetLiftSets(ctx context.Context, id uuid.UUID) ([]GetLiftSetsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLiftSets, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLiftSetsRow{}
	for rows.Next() {
		var i GetLiftSetsRow
		if err := rows.Scan(
			&i.ExerciseName,
			&i.Weight,
			&i.Reps,
			&i.DateLifted,
			&i.SetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSet = `-- name: GetSet :one
SELECT id, user_id FROM set 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSet(ctx context.Context, id uuid.UUID) (Set, error) {
	row := q.db.QueryRowContext(ctx, getSet, id)
	var i Set
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}
